apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/order_db
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: user123
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_CONFIG_LOCATION: /config/order/